name: release

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${GITHUB_REF_NAME}.zip ${{ github.event.repository.name }} -r  -x "*/.git/*" -x "*/.github/*"

      - uses: pyTooling/Actions/releaser@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: '${{ github.ref_name }}'
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
